name: Go CI with Redis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Install dependencies
      run: go mod tidy

    - name: Wait for Redis to be ready
      run: |
        until nc -z localhost 6379; do
          echo "Waiting for Redis..."
          sleep 1
        done

    # - name: Run tests
    #   env:
    #     REDIS_URL: redis://localhost:6379
    #   run: go test ./...

    - name: Build the project
      run: go build -v ./backend/main.go